export interface WeatherCodeInfo {
  code: number;
  label: string;
  description: string;
  icon: 'Sun' | 'Moon' | 'CloudSun' | 'CloudMoon' | 'Cloud' | 'CloudFog' | 'CloudDrizzle' | 'CloudRain' | 'CloudLighting' | 'CloudSnow' | 'Snowflake' | 'Zap' | 'Tornado';
  category: 'clear' | 'cloudy' | 'fog' | 'drizzle' | 'rain' | 'snow' | 'thunderstorm';
  bgGradientDay: string;
  bgGradientNight: string;
  accentColor: string;
}

export const WMO_WEATHER_CODES: Record<number, WeatherCodeInfo> = {
  0: {
    code: 0,
    label: 'Clear Sky',
    description: 'Bright and clear blue sky with max visibility.',
    icon: 'Sun',
    category: 'clear',
    bgGradientDay: 'from-amber-500/20 via-sky-400/20 to-blue-600/30',
    bgGradientNight: 'from-slate-900 via-indigo-950 to-slate-900',
    accentColor: 'amber-500',
  },
  1: {
    code: 1,
    label: 'Mainly Clear',
    description: 'Mostly clear skies with a few high thin clouds.',
    icon: 'CloudSun',
    category: 'clear',
    bgGradientDay: 'from-amber-400/20 via-sky-300/20 to-blue-500/25',
    bgGradientNight: 'from-slate-900 via-slate-950 to-indigo-950',
    accentColor: 'sky-500',
  },
  2: {
    code: 2,
    label: 'Partly Cloudy',
    description: 'Scattered clouds passing across the sky.',
    icon: 'CloudSun',
    category: 'cloudy',
    bgGradientDay: 'from-sky-400/20 via-slate-300/20 to-blue-600/20',
    bgGradientNight: 'from-slate-900 via-zinc-900 to-slate-950',
    accentColor: 'sky-400',
  },
  3: {
    code: 3,
    label: 'Overcast',
    description: 'Complete layer of clouds covering the sky.',
    icon: 'Cloud',
    category: 'cloudy',
    bgGradientDay: 'from-slate-400/25 via-zinc-400/20 to-slate-600/30',
    bgGradientNight: 'from-zinc-900 via-slate-900 to-zinc-950',
    accentColor: 'slate-400',
  },
  45: {
    code: 45,
    label: 'Foggy',
    description: 'Reduced visibility due to mist and dense fog.',
    icon: 'CloudFog',
    category: 'fog',
    bgGradientDay: 'from-zinc-400/30 via-slate-400/25 to-stone-500/30',
    bgGradientNight: 'from-zinc-950 via-slate-900 to-zinc-900',
    accentColor: 'zinc-400',
  },
  48: {
    code: 48,
    label: 'Depositing Rime Fog',
    description: 'Freezing fog forming frost on surfaces.',
    icon: 'CloudFog',
    category: 'fog',
    bgGradientDay: 'from-teal-300/20 via-slate-400/25 to-blue-400/20',
    bgGradientNight: 'from-slate-950 via-teal-950/40 to-slate-900',
    accentColor: 'teal-400',
  },
  51: {
    code: 51,
    label: 'Light Drizzle',
    description: 'Very light fine rain droplets falling.',
    icon: 'CloudDrizzle',
    category: 'drizzle',
    bgGradientDay: 'from-cyan-400/20 via-sky-500/20 to-slate-600/25',
    bgGradientNight: 'from-slate-950 via-cyan-950/50 to-slate-900',
    accentColor: 'cyan-400',
  },
  53: {
    code: 53,
    label: 'Moderate Drizzle',
    description: 'Steady light drizzle mist.',
    icon: 'CloudDrizzle',
    category: 'drizzle',
    bgGradientDay: 'from-cyan-500/25 via-blue-500/20 to-slate-700/30',
    bgGradientNight: 'from-slate-950 via-slate-900 to-cyan-950',
    accentColor: 'cyan-500',
  },
  55: {
    code: 55,
    label: 'Dense Drizzle',
    description: 'Heavy drizzle with noticeable accumulation.',
    icon: 'CloudDrizzle',
    category: 'drizzle',
    bgGradientDay: 'from-blue-500/30 via-slate-600/25 to-zinc-700/30',
    bgGradientNight: 'from-slate-950 via-blue-950/60 to-slate-900',
    accentColor: 'blue-400',
  },
  56: {
    code: 56,
    label: 'Light Freezing Drizzle',
    description: 'Light drizzle freezing on ground contact.',
    icon: 'CloudDrizzle',
    category: 'drizzle',
    bgGradientDay: 'from-sky-300/25 via-cyan-400/20 to-indigo-500/25',
    bgGradientNight: 'from-slate-950 via-indigo-950/60 to-sky-950',
    accentColor: 'sky-300',
  },
  57: {
    code: 57,
    label: 'Dense Freezing Drizzle',
    description: 'Heavy freezing drizzle causing icy patches.',
    icon: 'CloudDrizzle',
    category: 'drizzle',
    bgGradientDay: 'from-sky-400/30 via-indigo-400/25 to-slate-600/30',
    bgGradientNight: 'from-slate-950 via-sky-950/70 to-indigo-950',
    accentColor: 'sky-400',
  },
  61: {
    code: 61,
    label: 'Slight Rain',
    description: 'Light continuous rainfall.',
    icon: 'CloudRain',
    category: 'rain',
    bgGradientDay: 'from-blue-400/25 via-sky-500/20 to-slate-600/30',
    bgGradientNight: 'from-slate-950 via-blue-950/50 to-slate-900',
    accentColor: 'blue-400',
  },
  63: {
    code: 63,
    label: 'Moderate Rain',
    description: 'Steady moderate rain showers.',
    icon: 'CloudRain',
    category: 'rain',
    bgGradientDay: 'from-blue-500/30 via-sky-600/25 to-slate-700/35',
    bgGradientNight: 'from-slate-950 via-blue-950/70 to-slate-900',
    accentColor: 'blue-500',
  },
  65: {
    code: 65,
    label: 'Heavy Rain',
    description: 'Torrential rain with high precipitation rate.',
    icon: 'CloudRain',
    category: 'rain',
    bgGradientDay: 'from-blue-600/35 via-slate-700/30 to-indigo-900/40',
    bgGradientNight: 'from-slate-950 via-indigo-950 to-blue-950',
    accentColor: 'blue-600',
  },
  66: {
    code: 66,
    label: 'Light Freezing Rain',
    description: 'Light rain freezing upon impact.',
    icon: 'CloudRain',
    category: 'rain',
    bgGradientDay: 'from-cyan-400/30 via-blue-500/25 to-indigo-600/30',
    bgGradientNight: 'from-slate-950 via-cyan-950/60 to-indigo-950',
    accentColor: 'cyan-400',
  },
  67: {
    code: 67,
    label: 'Heavy Freezing Rain',
    description: 'Dangerous heavy freezing rain and black ice.',
    icon: 'CloudRain',
    category: 'rain',
    bgGradientDay: 'from-blue-600/40 via-cyan-600/30 to-slate-800/40',
    bgGradientNight: 'from-slate-950 via-slate-900 to-cyan-950',
    accentColor: 'cyan-500',
  },
  71: {
    code: 71,
    label: 'Slight Snowfall',
    description: 'Light flurries and gentle snow fall.',
    icon: 'CloudSnow',
    category: 'snow',
    bgGradientDay: 'from-sky-200/30 via-blue-300/25 to-indigo-400/25',
    bgGradientNight: 'from-slate-950 via-sky-950/50 to-slate-900',
    accentColor: 'sky-300',
  },
  73: {
    code: 73,
    label: 'Moderate Snowfall',
    description: 'Steady snow flakes accumulating on ground.',
    icon: 'CloudSnow',
    category: 'snow',
    bgGradientDay: 'from-blue-200/35 via-sky-300/30 to-indigo-500/30',
    bgGradientNight: 'from-slate-950 via-blue-950/60 to-indigo-950',
    accentColor: 'sky-200',
  },
  75: {
    code: 75,
    label: 'Heavy Snowfall',
    description: 'Heavy snow storm with potential accumulation.',
    icon: 'Snowflake',
    category: 'snow',
    bgGradientDay: 'from-sky-300/40 via-blue-400/35 to-indigo-700/40',
    bgGradientNight: 'from-slate-950 via-indigo-950 to-blue-950',
    accentColor: 'sky-100',
  },
  77: {
    code: 77,
    label: 'Snow Grains',
    description: 'Tiny white opaque ice grains falling.',
    icon: 'Snowflake',
    category: 'snow',
    bgGradientDay: 'from-sky-200/30 via-slate-300/25 to-blue-400/25',
    bgGradientNight: 'from-slate-950 via-slate-900 to-sky-950',
    accentColor: 'sky-200',
  },
  80: {
    code: 80,
    label: 'Slight Rain Showers',
    description: 'Passing light rain showers with sudden breaks.',
    icon: 'CloudRain',
    category: 'rain',
    bgGradientDay: 'from-sky-400/25 via-blue-400/20 to-slate-600/30',
    bgGradientNight: 'from-slate-950 via-sky-950/50 to-slate-900',
    accentColor: 'sky-400',
  },
  81: {
    code: 81,
    label: 'Moderate Rain Showers',
    description: 'Frequent showers of moderate intensity.',
    icon: 'CloudRain',
    category: 'rain',
    bgGradientDay: 'from-blue-500/30 via-sky-500/25 to-slate-700/35',
    bgGradientNight: 'from-slate-950 via-blue-950/60 to-slate-900',
    accentColor: 'blue-400',
  },
  82: {
    code: 82,
    label: 'Violent Rain Showers',
    description: 'Sudden intense downpours.',
    icon: 'CloudRain',
    category: 'rain',
    bgGradientDay: 'from-blue-600/40 via-indigo-700/35 to-slate-800/40',
    bgGradientNight: 'from-slate-950 via-indigo-950 to-slate-900',
    accentColor: 'indigo-400',
  },
  85: {
    code: 85,
    label: 'Slight Snow Showers',
    description: 'Brief passing snow showers.',
    icon: 'CloudSnow',
    category: 'snow',
    bgGradientDay: 'from-sky-300/30 via-blue-300/25 to-indigo-400/25',
    bgGradientNight: 'from-slate-950 via-sky-950/50 to-slate-900',
    accentColor: 'sky-300',
  },
  86: {
    code: 86,
    label: 'Heavy Snow Showers',
    description: 'Intense snow bursts with low visibility.',
    icon: 'Snowflake',
    category: 'snow',
    bgGradientDay: 'from-blue-300/40 via-sky-400/30 to-indigo-600/35',
    bgGradientNight: 'from-slate-950 via-indigo-950 to-sky-950',
    accentColor: 'sky-200',
  },
  95: {
    code: 95,
    label: 'Thunderstorm',
    description: 'Thunderstorm activity with lightning flashes.',
    icon: 'Zap',
    category: 'thunderstorm',
    bgGradientDay: 'from-purple-900/35 via-amber-600/20 to-slate-900/50',
    bgGradientNight: 'from-slate-950 via-purple-950 to-slate-900',
    accentColor: 'amber-400',
  },
  96: {
    code: 96,
    label: 'Thunderstorm & Light Hail',
    description: 'Storm with lightning and small hail ice.',
    icon: 'Zap',
    category: 'thunderstorm',
    bgGradientDay: 'from-violet-800/40 via-amber-500/25 to-slate-900/50',
    bgGradientNight: 'from-slate-950 via-violet-950 to-slate-950',
    accentColor: 'violet-400',
  },
  99: {
    code: 99,
    label: 'Thunderstorm & Heavy Hail',
    description: 'Severe thunderstorm with heavy hail damage risk.',
    icon: 'Zap',
    category: 'thunderstorm',
    bgGradientDay: 'from-purple-950/50 via-rose-900/30 to-slate-950/60',
    bgGradientNight: 'from-slate-950 via-purple-950/90 to-slate-950',
    accentColor: 'rose-400',
  },
};

export function getWeatherCodeInfo(code: number, isDay: boolean = true): WeatherCodeInfo {
  const info = WMO_WEATHER_CODES[code];
  if (info) return info;
  
  // Fallback for unexpected codes
  return {
    code,
    label: isDay ? 'Partly Cloudy' : 'Clear Night',
    description: 'Variable atmospheric conditions.',
    icon: isDay ? 'CloudSun' : 'CloudMoon',
    category: 'cloudy',
    bgGradientDay: 'from-sky-400/20 via-slate-300/20 to-blue-600/20',
    bgGradientNight: 'from-slate-900 via-zinc-900 to-slate-950',
    accentColor: 'sky-400',
  };
}
